package structs

type ConfigSet struct {
	Auth     AuthConfig     `yaml:"auth"`
	Download DownloadConfig `yaml:"download"`
	Lyrics   LyricsConfig   `yaml:"lyrics"`
	Artwork  ArtworkConfig  `yaml:"artwork"`
	Paths    PathsConfig    `yaml:"paths"`
	Naming   NamingConfig   `yaml:"naming"`
	Convert  ConvertConfig  `yaml:"convert"`
}

type AuthConfig struct {
	MediaUserToken     string `yaml:"media-user-token"`
	AuthorizationToken string `yaml:"authorization-token"`
	Storefront         string `yaml:"storefront"`
	Language           string `yaml:"language"`
}

type DownloadConfig struct {
	Codec     DownloadCodecConfig    `yaml:"codec"`
	Threads   int                    `yaml:"threads"`
	MaxMemory int                    `yaml:"max-memory"`
	M3U8      DownloadM3U8Config     `yaml:"m3u8"`
	Playlist  DownloadPlaylistConfig `yaml:"playlist"`
	MV        DownloadMVConfig       `yaml:"mv"`
}

type DownloadCodecConfig struct {
	AacType  string `yaml:"aac-type"`
	AlacMax  int    `yaml:"alac-max"`
	AtmosMax int    `yaml:"atmos-max"`
}

type DownloadM3U8Config struct {
	DecryptPort   string `yaml:"decrypt-port"`
	GetPort       string `yaml:"get-port"`
	GetFromDevice bool   `yaml:"get-from-device"`
	Mode          string `yaml:"mode"`
}

type DownloadPlaylistConfig struct {
	UseSongInfo        bool `yaml:"use-songinfo-for-playlist"`
	DownloadAlbumCover bool `yaml:"dl-albumcover-for-playlist"`
}

type DownloadMVConfig struct {
	AudioType string `yaml:"audio-type"`
	Max       int    `yaml:"max"`
}

type LyricsConfig struct {
	Enable   bool   `yaml:"enable"`
	Type     string `yaml:"type"`
	Format   string `yaml:"format"`
	Embed    bool   `yaml:"embed"`
	SaveFile bool   `yaml:"save-file"`
}

type ArtworkConfig struct {
	EmbedCover      bool   `yaml:"embed-cover"`
	Size            string `yaml:"size"`
	Format          string `yaml:"format"`
	SaveArtistCover bool   `yaml:"save-artist-cover"`
	SaveAnimated    bool   `yaml:"save-animated"`
	EmbyAnimated    bool   `yaml:"emby-animated"`
}

type PathsConfig struct {
	Alac  string `yaml:"alac"`
	Atmos string `yaml:"atmos"`
	Aac   string `yaml:"aac"`
}

type NamingConfig struct {
	Album             string `yaml:"album"`
	Playlist          string `yaml:"playlist"`
	Song              string `yaml:"song"`
	Artist            string `yaml:"artist"`
	ExplicitChoice    string `yaml:"explicit-choice"`
	CleanChoice       string `yaml:"clean-choice"`
	AppleMasterChoice string `yaml:"apple-master-choice"`
	LimitMax          int    `yaml:"limit-max"`
}

type ConvertConfig struct {
	Enable              bool   `yaml:"enable"`
	Format              string `yaml:"format"`
	KeepOriginal        bool   `yaml:"keep-original"`
	SkipIfSourceMatches bool   `yaml:"skip-if-source-matches"`
	FFmpegPath          string `yaml:"ffmpeg"`
	ExtraArgs           string `yaml:"extra-args"`
	WarnLossyToLossless bool   `yaml:"warn-lossy-to-lossless"`
	SkipLossyToLossless bool   `yaml:"skip-lossy-to-lossless"`
}

type ProgressCallback func(percent float64, msg string, speed float64)

type Counter struct {
	Unavailable int
	NotSong     int
	Error       int
	Success     int
	Total       int
}

// 艺术家页面
type AutoGeneratedArtist struct {
	Next string `json:"next"`
	Data []struct {
		ID         string `json:"id"`
		Type       string `json:"type"`
		Href       string `json:"href"`
		Attributes struct {
			Previews []struct {
				URL string `json:"url"`
			} `json:"previews"`
			Artwork struct {
				Width      int    `json:"width"`
				Height     int    `json:"height"`
				URL        string `json:"url"`
				BgColor    string `json:"bgColor"`
				TextColor1 string `json:"textColor1"`
				TextColor2 string `json:"textColor2"`
				TextColor3 string `json:"textColor3"`
				TextColor4 string `json:"textColor4"`
			} `json:"artwork"`
			ArtistName           string   `json:"artistName"`
			URL                  string   `json:"url"`
			DiscNumber           int      `json:"discNumber"`
			GenreNames           []string `json:"genreNames"`
			HasTimeSyncedLyrics  bool     `json:"hasTimeSyncedLyrics"`
			IsMasteredForItunes  bool     `json:"isMasteredForItunes"`
			IsAppleDigitalMaster bool     `json:"isAppleDigitalMaster"`
			ContentRating        string   `json:"contentRating"`
			DurationInMillis     int      `json:"durationInMillis"`
			ReleaseDate          string   `json:"releaseDate"`
			Name                 string   `json:"name"`
			Isrc                 string   `json:"isrc"`
			AudioTraits          []string `json:"audioTraits"`
			HasLyrics            bool     `json:"hasLyrics"`
			AlbumName            string   `json:"albumName"`
			PlayParams           struct {
				ID   string `json:"id"`
				Kind string `json:"kind"`
			} `json:"playParams"`
			TrackNumber  int    `json:"trackNumber"`
			AudioLocale  string `json:"audioLocale"`
			ComposerName string `json:"composerName"`
		} `json:"attributes"`
	} `json:"data"`
}
